/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface CdnPullZoneProps {
  label: string;
  originScheme?: "http" | "https";
  originDomain: string;
  vanityDomain?: string;
  ssl?: boolean;
  cors?: boolean;
  gzip?: boolean;
  blockAi?: boolean;
  blockBadBots?: boolean;
}

export type CdnPullZoneAttributes = {
  id: string;
  status: string;
  dateCreated: string;
  cdnUrl: string;
};

const defined = defineCrudResource<
  "Vultr.CdnPullZone",
  CdnPullZoneProps,
  CdnPullZoneAttributes
>({
  type: "Vultr.CdnPullZone",
  description: "A Vultr CDN pull zone.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/cdns/pull-zones",
  listKey: "pull_zones",
  wrapKey: "pull_zone",
  getPath: (id) => `/cdns/pull-zones/${id}`,
  
  
  
  replaceOnChange: ["originDomain"],
  toCreateBody: (props) =>
    compact({
    label: props.label,
    origin_scheme: props.originScheme,
    origin_domain: props.originDomain,
    vanity_domain: props.vanityDomain,
    ssl: props.ssl,
    cors: props.cors,
    gzip: props.gzip,
    block_ai: props.blockAi,
    block_bad_bots: props.blockBadBots,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      label: props.label,
      origin_scheme: props.originScheme,
      vanity_domain: props.vanityDomain,
      ssl: props.ssl,
      cors: props.cors,
      gzip: props.gzip,
      block_ai: props.blockAi,
      block_bad_bots: props.blockBadBots,
      },
      live,
      ["label", "origin_scheme", "vanity_domain", "ssl", "cors", "gzip", "block_ai", "block_bad_bots"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    status: live.status as string,
    dateCreated: live.date_created as string,
    cdnUrl: live.cdn_url as string,
  }),
});

/**
 * A Vultr CDN pull zone.
 * @resource
 */
export const CdnPullZone = defined.Resource;
export const CdnPullZoneProvider = defined.Provider;
