/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface OidcProviderProps {
  name: string;
  issuerUrl: string;
  clientId: string;
  clientSecret?: string;
}

export type OidcProviderAttributes = {
  id: string;
  dateCreated: string;
};

const defined = defineCrudResource<
  "Vultr.OidcProvider",
  OidcProviderProps,
  OidcProviderAttributes
>({
  type: "Vultr.OidcProvider",
  description: "A Vultr OIDC provider configuration.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/oidc/providers",
  listKey: "providers",
  wrapKey: "provider",
  getPath: (id) => `/oidc/providers/${id}`,
  
  
  
  replaceOnChange: ["issuerUrl"],
  toCreateBody: (props) =>
    compact({
    name: props.name,
    issuer_url: props.issuerUrl,
    client_id: props.clientId,
    client_secret: props.clientSecret,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      name: props.name,
      client_id: props.clientId,
      client_secret: props.clientSecret,
      },
      live,
      ["name", "client_id", "client_secret"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    dateCreated: live.date_created as string,
  }),
});

/**
 * A Vultr OIDC provider configuration.
 * @resource
 */
export const OidcProvider = defined.Resource;
export const OidcProviderProvider = defined.Provider;
