/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface StartupScriptProps {
  name: string;
  /** Script contents (base64 or plain text depending on type). */
  script: string;
  type?: "boot" | "pxe";
}

export type StartupScriptAttributes = {
  id: string;
  dateCreated: string;
  dateModified: string;
};

const defined = defineCrudResource<
  "Vultr.StartupScript",
  StartupScriptProps,
  StartupScriptAttributes
>({
  type: "Vultr.StartupScript",
  description: "A startup script executed on first boot of an instance.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/startup-scripts",
  listKey: "startup_scripts",
  wrapKey: "startup_script",
  getPath: (id) => `/startup-scripts/${id}`,
  
  
  
  replaceOnChange: ["type"],
  toCreateBody: (props) =>
    compact({
    name: props.name,
    script: props.script,
    type: props.type,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      name: props.name,
      script: props.script,
      },
      live,
      ["name", "script"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    dateCreated: live.date_created as string,
    dateModified: live.date_modified as string,
  }),
});

/**
 * A startup script executed on first boot of an instance.
 * @resource
 */
export const StartupScript = defined.Resource;
export const StartupScriptProvider = defined.Provider;
