/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface VirtualFileSystemStorageProps {
  region: string;
  label: string;
  /** Size in GB. */
  storageSize: number;
  diskType?: string;
}

export type VirtualFileSystemStorageAttributes = {
  id: string;
  status: string;
  dateCreated: string;
};

const defined = defineCrudResource<
  "Vultr.VirtualFileSystemStorage",
  VirtualFileSystemStorageProps,
  VirtualFileSystemStorageAttributes
>({
  type: "Vultr.VirtualFileSystemStorage",
  description: "A Vultr Virtual File System storage volume.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/vfs",
  listKey: "vfs_storages",
  wrapKey: "vfs_storage",
  getPath: (id) => `/vfs/${id}`,
  
  
  
  replaceOnChange: ["region", "diskType"],
  toCreateBody: (props) =>
    compact({
    region: props.region,
    label: props.label,
    storage_size: props.storageSize,
    disk_type: props.diskType,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      label: props.label,
      storage_size: props.storageSize,
      },
      live,
      ["label", "storage_size"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    status: live.status as string,
    dateCreated: live.date_created as string,
  }),
});

/**
 * A Vultr Virtual File System storage volume.
 * @resource
 */
export const VirtualFileSystemStorage = defined.Resource;
export const VirtualFileSystemStorageProvider = defined.Provider;
