/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface InferenceProps {
  label: string;
}

export type InferenceAttributes = {
  id: string;
  dateCreated: string;
  apiKey: string;
};

const defined = defineCrudResource<
  "Vultr.Subscription.Subscription",
  InferenceProps,
  InferenceAttributes
>({
  type: "Vultr.Subscription.Subscription",
  aliases: ["Vultr.Inference"],
  description: "A Vultr Serverless Subscription subscription.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/inference",
  listKey: "subscriptions",
  wrapKey: "subscription",
  getPath: (id) => `/inference/${id}`,
  
  
  
  replaceOnChange: [],
  toCreateBody: (props) =>
    compact({
    label: props.label,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      label: props.label,
      },
      live,
      ["label"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    dateCreated: live.date_created as string,
    apiKey: live.api_key as string,
  }),
});

/**
 * A Vultr Serverless Subscription subscription.
 * @resource
 */
export const Subscription = defined.Resource;
export const SubscriptionProvider = defined.Provider;
