/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface BlockStorageProps {
  region: string;
  sizeGb: number;
  label?: string;
  blockType?: string;
}

export type BlockStorageAttributes = {
  id: string;
  cost: number;
  status: string;
  attachedToInstance: string;
  dateCreated: string;
  mountId: string;
};

const defined = defineCrudResource<
  "Vultr.Volume.Volume",
  BlockStorageProps,
  BlockStorageAttributes
>({
  type: "Vultr.Volume.Volume",
  aliases: ["Vultr.BlockStorage"],
  description: "A Vultr block storage volume.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/blocks",
  listKey: "blocks",
  wrapKey: "block",
  getPath: (id) => `/blocks/${id}`,
  
  
  
  replaceOnChange: ["region", "blockType"],
  toCreateBody: (props) =>
    compact({
    region: props.region,
    size_gb: props.sizeGb,
    label: props.label,
    block_type: props.blockType,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      size_gb: props.sizeGb,
      label: props.label,
      },
      live,
      ["size_gb", "label"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    cost: live.cost as number,
    status: live.status as string,
    attachedToInstance: live.attached_to_instance as string,
    dateCreated: live.date_created as string,
    mountId: live.mount_id as string,
  }),
});

/**
 * A Vultr block storage volume.
 * @resource
 */
export const Volume = defined.Resource;
export const VolumeProvider = defined.Provider;
