/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface SshKeyProps {
  /** Label for the SSH key. */
  name: string;
  /** SSH public key contents. */
  sshKey: string;
}

export type SshKeyAttributes = {
  id: string;
  dateCreated: string;
};

const defined = defineCrudResource<
  "Vultr.SshKey.SshKey",
  SshKeyProps,
  SshKeyAttributes
>({
  type: "Vultr.SshKey.SshKey",
  aliases: ["Vultr.SshKey"],
  description: "An SSH public key registered on your Vultr account.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/ssh-keys",
  listKey: "ssh_keys",
  wrapKey: "ssh_key",
  getPath: (id) => `/ssh-keys/${id}`,
  
  
  
  replaceOnChange: [],
  toCreateBody: (props) =>
    compact({
    name: props.name,
    ssh_key: props.sshKey,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      name: props.name,
      ssh_key: props.sshKey,
      },
      live,
      ["name", "ssh_key"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    dateCreated: live.date_created as string,
  }),
});

/**
 * An SSH public key registered on your Vultr account.
 * @resource
 */
export const SshKey = defined.Resource;
export const SshKeyProvider = defined.Provider;
