/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface BareMetalProps {
  region: string;
  plan: string;
  osId?: number;
  appId?: number;
  imageId?: string;
  snapshotId?: string;
  label?: string;
  hostname?: string;
  tags?: ReadonlyArray<string>;
  enableIpv6?: boolean;
  sshKeyIds?: ReadonlyArray<string>;
  scriptId?: string;
  userData?: string;
  reservedIpv4?: string;
  vpcIds?: ReadonlyArray<string>;
}

export type BareMetalAttributes = {
  id: string;
  mainIp: string;
  status: string;
  defaultPassword: string;
  dateCreated: string;
  v6MainIp: string;
};

const defined = defineCrudResource<
  "Vultr.Server.Server",
  BareMetalProps,
  BareMetalAttributes
>({
  type: "Vultr.Server.Server",
  aliases: ["Vultr.BareMetal"],
  description: "A Vultr Bare Metal server.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/bare-metals",
  listKey: "bare_metals",
  wrapKey: "bare_metal",
  getPath: (id) => `/bare-metals/${id}`,
  
  
  
  replaceOnChange: ["region", "plan", "osId", "appId", "imageId", "snapshotId", "hostname", "enableIpv6"],
  toCreateBody: (props) =>
    compact({
    region: props.region,
    plan: props.plan,
    os_id: props.osId,
    app_id: props.appId,
    image_id: props.imageId,
    snapshot_id: props.snapshotId,
    label: props.label,
    hostname: props.hostname,
    tags: props.tags,
    enable_ipv6: props.enableIpv6,
    ssh_key_ids: props.sshKeyIds,
    script_id: props.scriptId,
    user_data: props.userData,
    reserved_ipv4: props.reservedIpv4,
    vpc_ids: props.vpcIds,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      label: props.label,
      tags: props.tags,
      reserved_ipv4: props.reservedIpv4,
      vpc_ids: props.vpcIds,
      },
      live,
      ["label", "tags", "reserved_ipv4", "vpc_ids"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    mainIp: live.main_ip as string,
    status: live.status as string,
    defaultPassword: live.default_password as string,
    dateCreated: live.date_created as string,
    v6MainIp: live.v6_main_ip as string,
  }),
});

/**
 * A Vultr Bare Metal server.
 * @resource
 */
export const Server = defined.Resource;
export const ServerProvider = defined.Provider;
