/* Generated by scripts/generate-resources.ts — edit the catalog to regenerate. */
import {
  compact,
  defineCrudResource,
  pickChanged,
  type JsonObject,
} from "../internal/defineResource.ts";

export interface CdnPushZoneProps {
  label: string;
  vanityDomain?: string;
  ssl?: boolean;
  cors?: boolean;
  gzip?: boolean;
  blockAi?: boolean;
  blockBadBots?: boolean;
}

export type CdnPushZoneAttributes = {
  id: string;
  status: string;
  dateCreated: string;
  cdnUrl: string;
};

const defined = defineCrudResource<
  "Vultr.CDN.PushZone",
  CdnPushZoneProps,
  CdnPushZoneAttributes
>({
  type: "Vultr.CDN.PushZone",
  aliases: ["Vultr.CdnPushZone"],
  description: "A Vultr CDN push zone.",
  stables: ["id"],
  idAttribute: "id",
  listPath: "/cdns/push-zones",
  listKey: "push_zones",
  wrapKey: "push_zone",
  getPath: (id) => `/cdns/push-zones/${id}`,
  
  
  
  replaceOnChange: [],
  toCreateBody: (props) =>
    compact({
    label: props.label,
    vanity_domain: props.vanityDomain,
    ssl: props.ssl,
    cors: props.cors,
    gzip: props.gzip,
    block_ai: props.blockAi,
    block_bad_bots: props.blockBadBots,
    }),
  toUpdateBody: (props, live) =>
    pickChanged(
      {
      label: props.label,
      vanity_domain: props.vanityDomain,
      ssl: props.ssl,
      cors: props.cors,
      gzip: props.gzip,
      block_ai: props.blockAi,
      block_bad_bots: props.blockBadBots,
      },
      live,
      ["label", "vanity_domain", "ssl", "cors", "gzip", "block_ai", "block_bad_bots"],
    ),
  toAttributes: (live, props) => ({
    id: live.id as string,
    status: live.status as string,
    dateCreated: live.date_created as string,
    cdnUrl: live.cdn_url as string,
  }),
});

/**
 * A Vultr CDN push zone.
 * @resource
 */
export const PushZone = defined.Resource;
export const PushZoneProvider = defined.Provider;
